### ISSUE TITLE
force Python 3.6 for OSX

### ISSUE THREAD

**Issue by rozdol** [aws-samples/chalice-workshop#30]
In `https://github.com/aws-samples/chalice-workshop/docs/source/env-setup.rst`

`git checkout f2a764e /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb` did not work

Digging the git history found that 'git checkout f2a764ef9 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb' works.

Change `f2a764e` to `f2a764ef9`

**Comment by kyleknap** [comment]
@rozdol What exact error do you get when running the below git command?
```
git checkout f2a764e /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
```
Or do you get an error? I definitely think we need to update the documentation here, but specifically I ran into problems where I was running ``git checkout`` outside of the git repository. I think the documentation needs to be updated to cd out into it first. So something like:
```
$ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
$ git checkout f2a764e Formula/python.rb
```
Does that work for you? It worked for me. I'm not sure if the extra ``f9`` part is needed.

**Comment by jamesls** [comment]
Closing the loop on this, I'm in the process of updating to use python3.7 so I think we can just remove this section entirely.
